name: "Build on main"
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  scheduler:
    name: Build Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'buster', 'stretch', 'bullseye' ]
    steps:
      - uses: actions/checkout@v1
      - name: Build php base image
        run: docker build -t openmage/php-php-base:${{ matrix.version }}-latest -f src/${{ matrix.version }}/src/Dockerfile src/${{ matrix.version }}/src/
