name: "Build Scheduler"
on:
  workflow_dispatch:
  schedule:
  - cron:  '30 3 * * 1'

jobs:
  scheduler:
    name: Build Trigger
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 'bullseye', 'bookworm' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: openmage/php-base:${{ matrix.version }}-latest
          context: ./src/${{ matrix.version }}/src
          file: ./src/${{ matrix.version }}/src/Dockerfile
